name: EXEC
author: super
main: me.superischroma.exec.EXEC
version: 0.0.1
api-version: 1.13
commands:
  executable:
    description: Create or delete an executable.
    usage: /<command> <statement>
  addinstruction:
    description: Add an instruction to an executable.
    usage: /<command> <statement> <...>
  removeinstruction:
    description: Remove an instruction from an executable.
    usage: /<command> <statement> <index>
  instructions:
    description: List the instructions of a given executable.
    usage: /<command> <statement>